# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "News"
  url = "#news"
  weight = 20

[[main]]
  name = "Featured Publications"
  url = "#featured"
  weight = 30

[[main]]
  name = "Service"
  url = "#service"
  weight = 40

[[main]]
  name = "Skills"
  url = "#skills"
  weight = 50

[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 60

[[main]]
  name = "Awards"
  url = "#awards"
  weight = 70

[[main]]
  name = "Work Experience"
  url = "#experience"
  weight=80

[[main]]
  name = "CV"
  url = "cv-chaopeng-en.pdf"
  weight = 90

[[main]]
  name = "简历"
  url = "cv-chaopeng-zh.pdf"
  weight = 100

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
