# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 'Home'
    url: '#about'
    weight: 10
  - name: 'News'
    url: '#news'
    weight: 20
  - name: 'Featured Publications'
    url: '#featured'
    weight: 30
  - name: 'Service'
    url: '#service'
    weight: 40
  - name: 'Teaching'
    url: '#teaching'
    weight: 45
  - name: 'Awards'
    url: '#awards'
    weight: 50
  - name: 'Work Experience'
    url: '#experience'
    weight: 60
  - name: 'CV'
    url: 'cv-chaopeng-en.pdf'
    weight: 70
  - name: '简历'
    url: 'cv-chaopeng-zh.pdf'
    weight: 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
